language: php

sudo: false

php:
  - 5.5

cache:
  directories:
    - $HOME/.composer/cache

addons:
  code_climate:
    repo_token: f63d88edcbb927b2f0ebd81d64d04e4713f43e762255e62e7a7873c7c953be1d

before_install:
  - composer self-update

install:
  - composer install

script:
  - vendor/bin/php-cs-fixer fix --config-file=./.php_cs --dry-run --diff -v
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - vendor/bin/test-reporter

notifications:
  email: false
