#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Localheinz\GitHub\ChangeLog;
use Symfony\Component\Console;

$application = new Console\Application();

$application->add(new ChangeLog\Console\PullRequestCommand());
$application->run();
